export const UPDATE_BRACKET_INDEX = 'UPDATE_BRACKET_INDEX';
export type UPDATE_BRACKET_INDEX = typeof UPDATE_BRACKET_INDEX;

export const UPDATE_BRACKET_ID = 'UPDATE_BRACKET_ID';
export type UPDATE_BRACKET_ID = typeof UPDATE_BRACKET_ID;

export const UPDATE_NODE = 'UPDATE_NODE';
export type UPDATE_NODE = typeof UPDATE_NODE;

export const RECEIVE_BRACKET_POST_RESPONSE = 'RECEIVE_BRACKET_POST_RESPONSE';
export type RECEIVE_BRACKET_POST_RESPONSE = typeof RECEIVE_BRACKET_POST_RESPONSE;

export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export type UPDATE_NOTIFICATION = typeof UPDATE_NOTIFICATION;

export const UPDATE_BRACKET = 'UPDATE_BRACKET';
export type UPDATE_BRACKET = typeof UPDATE_BRACKET;

export const TOGGLE_TOUCH = 'TOGGLE_TOUCH';
export type TOGGLE_TOUCH = typeof TOGGLE_TOUCH;

export const UPDATE_CANONICAL_BRACKETS = 'UPDATE_CANONICAL_BRACKETS';
export type UPDATE_CANONICAL_BRACKETS = typeof UPDATE_CANONICAL_BRACKETS;