export const UPDATE_BRACKETINDEX = 'UPDATE_BRACKETINDEX';
export type UPDATE_BRACKETINDEX = typeof UPDATE_BRACKETINDEX;

export const UPDATE_NODE = 'UPDATE_NODE';
export type UPDATE_NODE = typeof UPDATE_NODE;