export const UPDATE_BRACKET_INDEX = 'UPDATE_BRACKET_INDEX';
export type UPDATE_BRACKET_INDEX = typeof UPDATE_BRACKET_INDEX;

export const UPDATE_NODE = 'UPDATE_NODE';
export type UPDATE_NODE = typeof UPDATE_NODE;